# Generated by Django 3.0.7 on 2020-08-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_basics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basics',
            new_name='Basic',
        ),
    ]
