# Generated by Django 3.0.7 on 2020-08-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200830_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkExperience',
            new_name='Work',
        ),
    ]
