# Generated by Django 3.0.7 on 2020-08-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200830_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='ongoing',
        ),
        migrations.RemoveField(
            model_name='work',
            name='ongoing',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_date',
            field=models.DateField(),
        ),
    ]
